version: "3"
services:
  ros-husky:
    image: yhs/embodiedVLN:latest
    container_name: embodiedVLN
    network_mode: "host"
    devices:
      - /dev/prolific:/dev/prolific
    working_dir: "/root/catkin_ws"
    command: |-
      bash -c "
      cd ~/catkin_ws &&
      source ./devel/setup.bash &&
      sleep infinity
      "
